### ISSUE TITLE
Releasing scripts

### ISSUE THREAD

**Issue by koma111** [godlytalias/Bible-Database#13]
Hi, I'm currently developing a website for a Hungarian church community, and I'd like to add advanced search functionalities, which require the whole Bible, in Hungarian, to be stored in the database. I really don't want to manually add the entire Scripture to my database, but I've found the Hungarian translation on Wordproject.org, so it would be greatly appreciated if you could **release the scripts** you used **to extract the translations** found in this repo, so I can extract the Hungarian translation, and maybe contribute it here as a patch or merge request, for others to make good use of.

**Comment by godlytalias** [comment]
Hello @koma111, Sorry for late response. I have added the Hungarian version to the repo (https://github.com/godlytalias/Bible-Database/tree/master/Hungarian). But there are issues with some verses (For eg: 2Cor 13:14 - https://wordproject.org/bibles/hu/47/13.htm#0). It will be great if you can fix those and contribute back. Thanks

**Comment by koma111** [comment]
@godlytalias Not exactly what I requested. There are myriads of other translations in many many languages on Wordproject.org, you can't single-handedly export all of them, that would be very tedious. It would be much easier if you just _**added the script itself**_ that you use to extract languages and build the databases, _**to the repo**_. This way instead of you having to add every translation manually, people could extract their language if it isn't already in the repo, make corrections, and contribute.
Nevertheless, thanks for adding the Hungarian translation. I'll take a look and provide corrections in a separate issue.

**Comment by leonardsangoroh** [comment]
@godlytalias I agree with @koma111 . If you could kindly share the script you are using for translation so that other translations can be generated into respective formats without bothering you. Personally, I am working on a project whereby I need the respective formats of various bible translations. 
If you could kindly share the script, it would be highly appreciated. If not, kindly make it clear so that future visitors of this issue can know.
Thank you in advance.
